# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:           "/:title/"

# Setup
title:       'moshloop.com'
tagline:     ''
description: >
  My name is Moshe. I'm a <a href="https://gyshido.com">GyShiDo-San</a> / technologist and these are some of my ramblings.
url:         http://moshloop.com
enforce_ssl: mosheloop.com
baseurl:     /

author:
  name:   'Moshe Immerman'
  email:   moshe.immerman@gmail.com
  linkedin: moshe-immerman
  github:  moshloop

paginate: 10
excerpt_separator: <!-- more -->
exclude:
  - private
  - node_modules
plugins:
  - jekyll-redirect-from
  - jekyll-sitemap
  - jekyll-paginate
